config/routes.rb
Rails.application.routes.draw do

  resources :images

  resources :offenses

  resources :offense_types

  resources :locations

  post '/api/auth/phone'
  post '/api/auth/pin'
  get '/api/offense_type/all'
  get '/api/offense_type/get'
  post '/api/offense/post'

  resources :users

end

app/controllers/offenses_controller.rb
class OffensesController < ApplicationController
  before_action :set_offense, only: [:show, :edit, :update, :destroy]

  # GET /offenses
  # GET /offenses.json
  def index
    @offenses = Offense.all
    @images = Image.all
  end

  # GET /offenses/1
  # GET /offenses/1.json
  def show
  end

  # GET /offenses/new
  def new
    @offense = Offense.new
  end

  # GET /offenses/1/edit
  def edit
  end

  # POST /offenses
  # POST /offenses.json
  def create
    @offense = Offense.new(offense_params)
    respond_to do |format|
      if @offense.save
        format.html { redirect_to @offense, notice: 'Offense was successfully created.' }
        format.json { render :show, status: :created, location: @offense }
      else
        format.html { render :new }
        format.json { render json: @offense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offenses/1
  # PATCH/PUT /offenses/1.json
  def update
    respond_to do |format|
      if @offense.update(offense_params)
        format.html { redirect_to @offense, notice: 'Offense was successfully updated.' }
        format.json { render :show, status: :ok, location: @offense }
      else
        format.html { render :edit }
        format.json { render json: @offense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offenses/1
  # DELETE /offenses/1.json
  def destroy
    @offense.destroy
    respond_to do |format|
      format.html { redirect_to offenses_url, notice: 'Offense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offense
      @offense = Offense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offense_params
      params.require(:offense).permit(:time, :car_number, :comment, :location_id, :user_id, :offense_type_id)
    end


end

app/helpers/offenses_helper.rb
module OffensesHelper
end

app/views/offenses/_form.html.erb
<%= form_for(@offense) do |f| %>
  <% if @offense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offense.errors.count, "error") %> prohibited this offense from being saved:</h2>

      <ul>
      <% @offense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time%>
  </div>
  <div class="field">
    <%= f.label :car_number %><br>
    <%= f.text_field :car_number %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.collection_select(:location_id, Location.all, :id, :id) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select(:user_id, User.all, :id, :phone_number)%>
  </div>
  <div class="field">
    <%= f.label :offense_type_id %><br>
    <%= f.collection_select(:offense_type_id, OffenseType.all, :id, :title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offenses/edit.html.erb
<h1>Editing offense</h1>

<%= render 'form' %>

<%= link_to 'Show', @offense %> |
<%= link_to 'Back', offenses_path %>

app/views/offenses/index.html.erb
<h1 id="title">Spot The Offense</h1>

<div class="list">
    <% @offenses.each do |offense| %>
        <% @offense_images = @images.where(:offense_id => offense.id) %>
        <div class="list-item">
            <table class="images">
                <tbody>
                    <tr>
                        <td>
                            <%unless @offense_images[0].blank? %>
                                <%= image_tag(@offense_images[0].path) %>
                             <% end %>
                        </td>
                        <td>
                      <td>
                        <%unless @offense_images[1].blank? %>
                            <%= image_tag(@offense_images[1].path) %>
                        <% end %>
                      </td>
                      <td>
                    </tr>
                <tr>
                    <td>
                      <%unless @offense_images[2].blank? %>
                          <%= image_tag(@offense_images[2].path) %>
                      <% end %>
                    </td>
                    <td>
                    <td>
                      <%unless @offense_images[3].blank? %>
                          <%= image_tag(@offense_images[3].path) %>
                      <% end %>
                    </td>
                    <td>
                </tr>
                </tbody>
         </table>

    <div class="map">
      <%= image_tag "http://maps.google.com/maps/api/staticmap?size=550x150&sensor=false&zoom=16&markers=#{offense.location.latitude}%2C#{offense.location.longitude}", class: "map" %>
    </div>

    <div class="datetime">
      <span class="date"><%= offense.time.strftime("%d.%m.%Y",) %></span>
      <span class="time"><%= offense.time.strftime("%H:%M") %></span>
    </div>

    <div class="offense-type">
      <p><%= OffenseType.find(offense.offense_type).title %></p>
    </div>

    <div class="comment">
      <p><%= offense.comment %></p>
    </div>

  </div>
  <% end %>
</div>

<!--<table>-->
  <!--<thead>-->
    <!--<tr>-->
      <!--<th>Id</th>-->
      <!--<th>Time</th>-->
      <!--<th>Car number</th>-->
      <!--<th>Comment</th>-->
      <!--<th>Location</th>-->
      <!--<th>User</th>-->
      <!--<th>Offense type</th>-->
      <!--<th>Images</th>-->
      <!--<th colspan="3"></th>-->
    <!--</tr>-->
  <!--</thead>-->

  <!--<tbody>-->
    <!--<% @offenses.each do |offense|%>-->
        <!--<% @offense_images = @images.where(:offense_id => offense.id) %>-->
      <!--<tr>-->
        <!--<td><%= offense.id%></td>-->
        <!--<td><%= offense.time.to_s %></td>-->
        <!--<td><%= offense.car_number %></td>-->
        <!--<td><%= offense.comment %></td>-->
        <!--<td><%= offense.location.latitude.to_s + "   "+ offense.location.longitude.to_s %></td>-->
        <!--<td><%= offense.user.phone_number %></td>-->
        <!--<td><%= offense.offense_type.title %></td>-->
        <!--<td>-->
          <!--<% @offense_images.each do |i|%>-->
            <!--<%= image_tag(i.path, class: 'list_image') %>-->
          <!--<% end %>-->
        <!--</td>-->
        <!--<td><%= link_to 'Show', offense %></td>-->
        <!--<td><%= link_to 'Edit', edit_offense_path(offense) %></td>-->
        <!--<td><%= link_to 'Destroy', offense, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      <!--</tr>-->
    <!--<% end %>-->
  <!--</tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New Offense', new_offense_path %>-->

app/views/offenses/new.html.erb
<h1>New offense</h1>

<%= render 'form' %>

<%= link_to 'Back', offenses_path %>

app/views/offenses/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Time:</strong>
  <%= @offense.time %>
</p>

<p>
  <strong>Car number:</strong>
  <%= @offense.car_number %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @offense.comment %>
</p>

<p>
  <strong>Location:</strong>
  <%= @offense.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @offense.user %>
</p>

<p>
  <strong>Offense type:</strong>
  <%= @offense.offense_type %>
</p>

<%= link_to 'Edit', edit_offense_path(@offense) %> |
<%= link_to 'Back', offenses_path %>