config/routes.rb
Rails.application.routes.draw do

  resources :images

  resources :offenses

  resources :offense_types

  resources :locations

  post '/api/auth/phone'
  post '/api/auth/pin'
  get '/api/offense_type/all'
  get '/api/offense_type/get'
  post '/api/offense/post'

  resources :users

end

app/controllers/api/offense_type_controller.rb
class Api::OffenseTypeController < ApplicationController
  skip_before_filter :verify_authenticity_token

  require 'response'
  def all
    @offense_types = OffenseType.all

    @offenses = Array.new
    @offense_types.each do |ot|
      @offenses << {
          id: ot.id,
          title: ot.title,
          small_image: "http://" +  request.host_with_port + ot.path_to_small_image
      }
    end
    render json: @offenses.to_json
  end

  def get
    if params[:id].blank?
      render json: Response.new("405", "check id param").to_json
      return
    end

    @id = params[:id]

    if OffenseType.exists?(@id)
      @offence_type = OffenseType.find(@id)
    else
      render json: Response.new("406", "not found").to_json
      return
    end

    render json:  {
        id: @offence_type.id,
        description: @offence_type.description,
        big_image: "http://" + request.host_with_port + @offence_type.path_to_big_image
    }.to_json
  end


end

app/controllers/offense_types_controller.rb
class OffenseTypesController < ApplicationController
  before_action :set_offense_type, only: [:show,:destroy]

  @@path_to_image = "/offense_type/"
  # GET /offense_types
  # GET /offense_types.json
  def index
    @offense_types = OffenseType.all
  end

  # GET /offense_types/1
  # GET /offense_types/1.json
  def show
  end

  # GET /offense_types/new
  def new
    @offense_type = OffenseType.new
  end

  # GET /offense_types/1/edit
  def edit
  end

  # POST /offense_types
  # POST /offense_types.json
  def create
    @offense_type = OffenseType.new(offense_type_params)

    small_pic = params[:offense_type][:path_to_small_image]
    big_pic = params[:offense_type][:path_to_big_image]

    @offense_type.path_to_small_image =  @@path_to_image + small_pic.original_filename
    @offense_type.path_to_big_image = @@path_to_image + big_pic.original_filename

    FileUtils.copy(small_pic.tempfile, "#{Rails.public_path}" + @offense_type.path_to_small_image)
    FileUtils.copy(big_pic.tempfile, "#{Rails.public_path}" + @offense_type.path_to_big_image)

    respond_to do |format|
      if @offense_type.save
        format.html { redirect_to @offense_type, notice: 'Offense type was successfully created.' }
        format.json { render :show}
      else
        format.html { render :new }
        format.json { render json: @offense_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    FileUtils.remove("#{Rails.public_path}" + @offense_type.path_to_small_image, force:true)
    FileUtils.remove("#{Rails.public_path}" + @offense_type.path_to_big_image, force:true)
    @offense_type.destroy
    respond_to do |format|
      format.html { redirect_to offense_types_url, notice: 'Offense type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offense_type
      @offense_type = OffenseType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offense_type_params
      params.require(:offense_type).permit(:title, :description, :path_to_small_image, :path_to_big_image)
    end
end

app/views/offense_types/_form.html.erb
<%= form_for(@offense_type, :html => {:multipart => true}) do |f| %>
  <% if @offense_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offense_type.errors.count, "error") %> prohibited this offense_type from being saved:</h2>

      <ul>
      <% @offense_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Title" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Small image" %><br>
    <%= f.file_field :path_to_small_image %>
  </div>
  <div class="field">
    <%= f.label "Big image" %><br>
    <%= f.file_field :path_to_big_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offense_types/index.html.erb
<h1>Listing Offense Types</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Small image</th>
      <th>Big image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offense_types.each do |offense_type| %>
      <tr>
        <td><%= offense_type.title %></td>
        <td><%= offense_type.description %></td>
        <td><%= image_tag(offense_type.path_to_small_image, class: 'list_image') %></td>
        <td><%= image_tag(offense_type.path_to_big_image, class: 'list_image') %></td>
        <td><%= link_to 'Show', offense_type %></td>
        <td><%= link_to 'Destroy', offense_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offense type', new_offense_type_path %>

app/views/offense_types/new.html.erb
<h1>New Offense Type</h1>

<%= render 'form' %>

<%= link_to 'Back', offense_types_path %>

app/views/offense_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offense_type.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offense_type.description %>
</p>

<p>
  <strong>Small image:</strong>
  <%= @offense_type.path_to_small_image %>
</p>

<p>
  <strong>Big image:</strong>
  <%= @offense_type.path_to_big_image %>
</p>

<%= link_to 'Edit', edit_offense_type_path(@offense_type) %> |
<%= link_to 'Back', offense_types_path %>